version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=HabitAdmin2026!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      # .NET API'nin MSSQL konteynerine bağlanması için gerekli ayar
      - ConnectionStrings__DefaultConnection=Server=db34323.public.databaseasp.net;Database=db34323;User Id=db34323;Password=HabitAdmin2026!;TrustServerCertificate=True;
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mssql-data: